### ISSUE TITLE
[로그인화면] 추가할것들 혹은 미기재 항목

### ISSUE THREAD

**Issue by tmddus10** [wooritech/ilab-user-manual#19]
![3](https://user-images.githubusercontent.com/35017374/35030427-3d281ef4-fba2-11e7-9e7f-5877680aff21.png)

1. 보안 로그인이 없음. (최신버전 사진변경필요)

2. 버전에 대한 설명 미기재 (날짜, 일련번호)

3. 로그인 버튼과 캔슬버튼에 대한 설명 부족.

이 밖에도 기술상으로 가능하다면 실행시 공지사항 팝업창도 있다면 좋을거 같습니다.
아이랩은 자동업데이트지만, 종종 메뉴가 바뀌거나 ui가 개선되어도 자신이 자주 쓰는 
분야가 아니라면 알기 힘들거 같습니다.

**Comment by onlydel** [comment]
공지사항 팝업 기능은 이미 있습니다. 변경된 기능에 대한 내용을 공지하자는 의견은 아주 좋은 것 같습니다.
