### ISSUE TITLE
[006재무영업관리] 관련 메인 목차 및 하위 목차 페이지에 오류가 있어 링크가 안되는 메뉴가 있습니다.

### ISSUE THREAD

**Issue by onlydel** [wooritech/ilab-user-manual#2]
### 문제
파일명과 목차에 각각 공백문자가 들어 있어서 링크가 안되는 경우가 있습니다.
- summary.md
- 006재무영업관리.md

### 공백은?
- 대쉬(-)로 표현하거나 
- 목차에서는 아예 제거합니다.

### 예를 들어 
제목이 "지부별 입금관리" 라면
- 파일명은 "지부별입금관리.md"
- 목차링크에는 `[지부별 입금관리](/006재무영업관리/지부별입금관리.md)`로 표현합니다.

![image](https://user-images.githubusercontent.com/6207238/34552266-cda5e842-f163-11e7-9b93-bdb399d51a33.png)

**Comment by KIMSANGYEOB** [comment]
파일명과 목차의 공백을 제거하였습니다.
