### ISSUE TITLE
[/000공통기능/01설치및실행.html] 줄바꿈 오류

### ISSUE THREAD

**Issue by onlydel** [wooritech/ilab-user-manual#4]
첫번째 줄에 줄바꿈 오류 수정 필요.

https://help.ilabs.co.kr/000공통기능/01설치및실행.html

**Comment by onlydel** [comment]
이거 꼭 바꿔야 되나?

**Comment by onlydel** [comment]
같은 문맥이니 하나의 문단으로 구성하는게 맞을것 같습니다.

**Comment by tmddus10** [comment]
https://help.ilabs.co.kr/006재무영업관리/계산서%20발행일%20관리.html

**Comment by KIMSANGYEOB** [comment]
내용과 문단을 좀 더 명확하게 맞춰 수정하였습니다.

**Comment by tmddus10** [comment]
확인하였습니다. 잘 맞게 수정되었습니다.
