### ISSUE TITLE
004-06결과등록화면 3.0 매뉴얼 수정 목표

### ISSUE THREAD

**Issue by tmddus10** [wooritech/ilab-user-manual#43]
- [x]  검토요청 이미지와 설명 마무리

- [x]  규격편집 검사항목관리에 링크연결

- [x]  시험법 편집 이미지 추가 및 수정

- [x]  시험법 변경 이미지 추가 및 수정

**Comment by graytails** [comment]
목표 일정 잡기
완료된 것은 체크
