### ISSUE TITLE
https://help.ilabs.co.kr/002공통코드관리/사용자관리.html 오류

### ISSUE THREAD

**Issue by tmddus10** [wooritech/ilab-user-manual#8]
부서를 추가하거나 관리하려고 하면 오류가 걸립니다. 일시적인 오류인지 제 컴퓨터에서만 그런지
모르겠습니다만, 지속적으로 오류가 발생하네요
![image](https://user-images.githubusercontent.com/35017374/34659665-b692ffa0-f47e-11e7-994d-ca6e28d70745.png)

**Comment by onlydel** [comment]
아이랩 프로그램 오류는 서비스요청을 통해서 문의하세요.
이곳에는 아이랩 도움말 사이트, 동영상 도움말등에 대한 이슈만 기록하기로 합시다.

**Comment by tmddus10** [comment]
예 알겠습니다. 도움말에 관련된 이슈만 올리고
아이랩 프로그램 오류는 따로 모아서 전달하도록 하겠습니다.

**Comment by KIMSANGYEOB** [comment]
closed 하겠습니다
